#!/usr/bin/env python3
"""Build a DaySchedule iframe snippet without rewriting the app's CSS or JS.

Default: a self-contained srcdoc iframe for an approved custom HTML host.
--app-url: an HTTPS iframe for the modern SharePoint Embed web part.
The tenant must allow the URL, and the app host must allow framing.
"""

from __future__ import annotations

import argparse
import html
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
SOURCE = DIST / "DaySchedule.html"
OUTPUT = DIST / "DaySchedule.sharepoint.html"

HEADER = """<!--
DaySchedule iframe build. Generated by tools/build-sharepoint-embed.py.
The app owns its iframe document: styles, keyboard shortcuts, dialogs, and
print preparation cannot accidentally target elements on the hosting page.
The standalone app's CSP and MIT notice remain inside the frame.

The default srcdoc snippet requires an approved custom HTML host. Modern
SharePoint's ordinary Embed web part is a different route: host DaySchedule.html
at an approved HTTPS URL and generate its snippet using --app-url.

A same-origin srcdoc frame is not a security boundary against host scripts.
Only use a trusted host; its CSP can also restrict this frame. A cross-origin
HTTPS frame isolates the app from host scripts but native file pickers are
restricted there. Open the app URL in its own tab for reliable file autosave
and standalone printing. Fallback saves download a fresh .schedule copy.

One editor at a time: frames using the same origin share browser persistence.
Set --height to fit the available host zone (default 900 CSS pixels).
-->
"""


class AppPolicyParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.in_head = False
        self.policies: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "head":
            self.in_head = True
        attributes = dict(attrs)
        if self.in_head and tag == "meta" and (attributes.get("http-equiv") or "").lower() == "content-security-policy":
            self.policies.append(attributes.get("content") or "")

    def handle_endtag(self, tag: str) -> None:
        if tag == "head":
            self.in_head = False


def https_url(value: str) -> str:
    if "\\" in value or any(ord(character) <= 32 or ord(character) == 127 for character in value):
        raise argparse.ArgumentTypeError("The app URL must not contain backslashes, whitespace, or control characters.")
    try:
        parsed = urlsplit(value)
        valid = parsed.scheme == "https" and bool(parsed.hostname) and parsed.username is None and parsed.password is None
        parsed.port  # Reject malformed ports as well as malformed host syntax.
    except ValueError:
        valid = False
    if not valid:
        raise argparse.ArgumentTypeError("Use an absolute HTTPS app URL without credentials.")
    return value


def positive_height(value: str) -> int:
    try:
        height = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError("Height must be a positive number of CSS pixels.") from error
    if height < 1:
        raise argparse.ArgumentTypeError("Height must be a positive number of CSS pixels.")
    return height


def build_embed(app_document: str | None, app_url: str | None, height: int) -> str:
    if app_url:
        source = 'src="' + html.escape(app_url, quote=True) + '"'
    else:
        policy = AppPolicyParser()
        policy.feed(app_document or "")
        directives = [directive.split() for directive in policy.policies[0].split(";")] if len(policy.policies) == 1 else []
        connections = [directive for directive in directives if directive and directive[0].lower() == "connect-src"]
        if connections != [["connect-src", "'none'"]]:
            raise ValueError("The standalone document needs one head Content-Security-Policy with connect-src 'none'.")
        source = 'srcdoc="' + html.escape(app_document, quote=True) + '"'
    # No parent-page scripts, generated CSS selectors, window-global guards,
    # or fixed element IDs. A remounted iframe initializes its own document.
    return (
        HEADER
        + '<iframe title="DaySchedule schedule editor" '
        + source
        + f' width="100%" height="{height}" style="display:block;border:0;width:100%;"'
        + ' referrerpolicy="no-referrer"></iframe>\n'
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dist", action="store_true", help="Build the current standalone app before creating the snippet.")
    parser.add_argument("--app-url", type=https_url, help="Approved HTTPS app URL for a modern SharePoint Embed web part.")
    parser.add_argument("--height", type=positive_height, default=900, help="Iframe height in CSS pixels (default: 900).")
    args = parser.parse_args()
    if args.build_dist:
        subprocess.run([sys.executable, str(ROOT / "tools/build-single-html.py")], check=True)
    document = None
    if not args.app_url:
        if not SOURCE.exists():
            parser.error("Standalone app missing. Pass --build-dist or run tools/build-single-html.py first.")
        document = SOURCE.read_text(encoding="utf-8")
    output = build_embed(document, args.app_url, args.height)
    DIST.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
